### ISSUE TITLE
64Bit

### ISSUE THREAD

**Issue by onryldz** [Coldzer0/IDA-For-Delphi#1]
Hi, 
Supported for x64, XE and upper versions?

**Comment by Coldzer0** [comment]
i'm working on it right now
i'll update the script today

**Comment by Coldzer0** [comment]
@onryldz 
i finish a init version to test https://github.com/Coldzer0/IDA-For-Delphi/commit/f22a649ca322de4e29a0e0317530ee6100d7827a 
if you can test and give a feedback will be appreciated

**Comment by onryldz** [comment]
Hi, thanks for this perfect working. its awesome, 
but i think have a very small problem.

Its error: 
D01990: can't rename byte as '_DE_BitBtn2Click' because the name is already used in the program.

it's can error resolvable?

**Comment by Coldzer0** [comment]
@onryldz thanks for testing 
i update the code and add small enhancement to it
and now it won't show this warning message again if function already named .

i will close this for now , you can reopen in any time if u had a problem .
