### ISSUE TITLE
Not working for ida 7

### ISSUE THREAD

**Issue by karpiyon** [Coldzer0/IDA-For-Delphi#3]
Hi, 
I can' find the "rename delphi" script, where can it be downloaded from?
I placed "Delphi.py" under the plugin directory of IDA and all is stuck...

**Comment by Coldzer0** [comment]
the version in the images is IDA Pro 7
and Delphi.py is what you need

don't place it in plugins directory 

please follow the images in readme file .

**Comment by Coldzer0** [comment]
i will close this for now , if you have any problem please open this issue again 
thanks

**Comment by karpiyon** [comment]
thanks
