### ISSUE TITLE
unable to find the event constructor

### ISSUE THREAD

**Issue by dummys** [Coldzer0/IDA-For-Delphi#5]
Hello,

I have a delphi binary x86, and I can't find the event constructor based on your pattern. Do you have another way finding it ? 
The version of delphi compiler is: Embarcadero Delphi for Win32 compiler version 33.0 (26.0.36039.7899) and exeinfope give Borland delphi 2013 XE5

**Comment by Coldzer0** [comment]
First it must be a GUI app not console app

And if you can upload it so i can check it.

**Comment by dummys** [comment]
It's a GUI app. The problem is that I can't share it here. Can we do some private chat ? perhaps irc ?

**Comment by Coldzer0** [comment]
mail me at : 

> coldzer0[at]protonmail[dot]ch

**Comment by dummys** [comment]
done
