### ISSUE TITLE
Wrong number or type of args for overloaded func add_bpt

### ISSUE THREAD

**Issue by vigri** [Coldzer0/IDA-For-Delphi#6]
Hello,

I would like to report a possible bug after trying your script out.

When I execute your script I get `Wrong number or type of arguments for overloaded function 'add_bpt'`

![image](https://user-images.githubusercontent.com/2580723/79028637-276ab380-7b91-11ea-9498-c45fbad74e9e.png)

**Comment by Coldzer0** [comment]
Thanks, I'll update it to support IDA v 7.x

**Comment by Coldzer0** [comment]
The last update now supports IDA 7.7
